TOL = 1e-6

RES = WIDTH, HEIGHT = 1200, 900
FPS = 60
TICK = 60

MAP_TileX = 60
MAP_TileY = 60

MAP_Cols = WIDTH / MAP_TileX
MAP_Rows = HEIGHT / MAP_TileY

THRESHOLD_LEFT = WIDTH / 4
THRESHOLD_RIGHT = WIDTH * 3 / 4

# MAP_StepX = WIDTH / MAP_TileX
# MAP_stepY = HEIGHT / MAP_TileY
